# Generated by Django 2.2 on 2019-12-14 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(default='default.jpg', upload_to='Book_covers')),
                ('published', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], max_length=2)),
                ('genre', multiselectfield.db.fields.MultiSelectField(choices=[('R', 'Romance'), ('D', 'Drama'), ('F', 'Fiction'), ('M', 'Mystery')], max_length=7)),
                ('date_added', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='author.Author')),
                ('book_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
